### PR TITLE
Support rocket-chip's JTAG DTM

### PR DESCRIPTION
**Pull request by mwachs5**
I'm not really expecting this to be merged, just submitting it for your feedback.

With this, i was able to replace the  JTAG DTM in rocket-chip. 

I experimented with the asynchronously reset logic, but I'm not sure I'm using these as you'd expect. Here's what I currently have:

TRSTn -- external active-low input presumably from off-chip, but must be synchronized to TCK for dassert outside of this logic. Asynchronously resets jtagState to TEST_LOGIC_RESET. This signal should be totally optional -- if tied high the design should still work.

io.control.reset -- This is equivalent to (jtagState == TEST_LOGIC_RESET) but since that is asynchronously reset, it is itself an asynchronously asserted reset signal. I am taking that and using it as the reset for most of the logic running off TCK.

io.control.fsmAsyncReset -- this is driven by something I'm calling "jtagPOReset". I think in general you don't want to 

For all my debug logic I need to think about what reset domain it should really be in.

When you clear IR, it is not done asynchronously. What does the spec say for this? Should this be driven by the async reset as well?

In rocket-chip I believe it is the standard to have the master side of the interface as the non-flipped version, so here I flipped JTAGIO to match.

Finally someone suggested that  the negative edge clocking issues should be pushed to the edge of your design / chip, unless you really have a good reason to do it within the logic. Perhaps this could be added as an option in jtagTap and a utility function to apply  at the SoC top level.

### CODE REVIEW

**Comment by ducky64** [comment]
Flipping JtagIO: makes sense, I'll implement that.

TRSTn: I think that if TRSTn is implemented, then fsmAsyncReset is unnecessary. TRSTn should reset everything and can be used for POR. This could be done easily once there is asynchronous reset support in Chisel, and should also clear the IR. I think it's required that the IR be cleared so that IDCODE is selected for DR scan.

As for reset domains: this is a tricky question. There are two reset sources: TRSTn and Test-Logic-Reset state (io.control.reset). Test-Logic-Reset state should essentially be a superset (of sorts) of TRSTn and should be used for resetting user debug logic. It can't be used for the FSM, since the FSM would then never move out of reset.

I can't think of a particularly clean API for this though - mostly because the Chains need to be instantiated before the JTAG module is instantiated, but the Chains also should be reset from the output of the JTAG module (and that has to be handled within a Module or block, making it difficult to get the Chains out of that scope). The current way (pipe the reset output of the TAP into the enclosing module's reset, and have the TAP FSM ignore that reset in favor of TRSTn) may be the least worst solution. 

If TRSTn is tied high, there would need to be some kind of POR to ensure the FSM initializes in Test-Logic-Reset. I think some actions are state-dependent - it would suck to have it initialize in Run-Test-Idle with boundary scan selected and take over all your IO...

Pushing out negative edge clocking: there could be an optional argument that makes outputs positive edge clocked, for internal TAP chains. I'd like the generator to be as easy and foolproof as possible (within the abstraction boundaries). It's on the to-do list, but low priority.

**Comment by mwachs5** [comment]
Ok, I am reviewing the spec now for the async reset requirements. Basically you *have* to asynchronously reset things at power up, either with POR circuitry and/or TRSTn, but not with the system reset. Figure 6-8 shows this nicely.

Also, IR should be asynchronously reset by TRSTn as well (see 7.2.1 f), and by the "reset" signal generated from the state logic. It's unclear whether it would get reset by POR circuitry, but by the rule that TRSTn and POR circuitry are supposed to be equivalent functionality, I would say yes.

Taking a fresh look at how I'm wiring everything up to make sure it's to spec.

**Comment by mwachs5** [comment]
(anyway I agree with everything you said, just wrapping my own head around it)

**Comment by mwachs5** [comment]
Chain needs to support  async reset functionality, driven from the control.reset

**Comment by ducky64** [comment]
I think one proposal for async reset was to have that at the Module/block level where it would propagate downwards, and if that is implemented then Chain should have async reset too.

**Comment by mwachs5** [comment]
I have incorporated this code into rocket-chip directly, so closing this PR.

**Pull request closed without merging**
